### PR TITLE
CCL-22: Fix for regex and nregex

### PR DESCRIPTION
**Pull request by javierlores**

### CODE REVIEW

**Comment by jtnelson** [comment]
@javierlores Can you figure out why `testReproIX5A` is now failing in `JavaCCParserLogicTest" and fix it? Thanks!

**Comment by javierlores** [comment]
Looks like it's auto-quoting the LIKE operator now. Correct me if I'm wrong, the like operator is not allowed to be quoted correct? e.g. `LIKE "%Accounting And Business/management%"` is not valid?

**Comment by jtnelson** [comment]
@javierlores All of the operators should be able to accept values that are quoted. In the example above, the value is quoted because it contains spaces

**Comment by javierlores** [comment]
Hm... Well so what I was doing for the LIKE operator was treating the % as the double quote operator/delimiter because it seems redundant to add both the double quotes and percent delimiters, so it was still accepting spaces. So, the possible fixes I see are 
1. Add an exception to the auto-quoting mechanism for the LIKE operator
2. Change the rules for the grammar to not treat the % symbol as quotes and enforce Quotes when spaces are used in the LIKE operator

I lean towards 1. since, unless I'm missing something, the % and double quote operator seem redundant in this case.

**Comment by jtnelson** [comment]
@javierlores let's go with option #2. Unfortunately, the quoting mechanism in the ValueSymbol isn't necessarily aware of the associated operator when building the criteria.

**Pull request merged**
